### PR TITLE
Incorporated speed into Npc indefinite movement in auto_gen_movement() in npc_move.c in NPC

### LINKED ISSUE #1306: Incorporate speed depending on NPC Player Class into NPC indefinite movement in auto_gen_movement()
NPC indefinite movement paths should be dependent on speed attributes associated with their specific class. Right now the time the NPC spends in each room is completely random, so the min and max times should change based on the class. We will determine how to access playerclass stats through the hash table and come up with a viable strategy to convert the speed stat into a multiplier that affects the minimum and maximum times NPCs on an indefinite movement path spend in a room.

### LINKED ISSUE #1519: Implement Testing for speed auto_gen_movement functionality inside test_npc_move.c
In Issue #1306 , we adjusted the auto_gen_movement() function in npc_move.c to include a multiplier based on the speed stat of the NPC's class that affects the time spent in each room on an indefinite movement path. The corresponding test Test(npc_mov, auto_gen_movement_indefinite) does not currently account for the implementation of this feature and is thus crashing, so we have commented it out for now and are creating a new issue to adjust this test so it correctly tests the implementation of this new feature. The testing for the auto_gen_movment of NPC_MOVEMENT_INDEFINITE broke after we changed the implementation of how speed is generated. 

We have decided to repudiate these tests to reflect the changes we made from a previous issue

### PR DESCRIPTION
**Pull request by jroven**
Vincent and I finally got a successful build after trying to incorporate speed stat multiplier into auto_gen_movement() in npc_move.c for issue #1306.

We used this stats hash table function found in stats.h in game-state to change the speed multipliers, and implemented this into auto_gen_movement(). However, because the Test case for Test(npc_mov, auto_gen_movement_indefinite was not written for this change, it crashed. We decided that this can be a separate task of adjusting the test to work for our new implementation/feature, and will close this issue now.

Note: We attempted to create a pull request of this in #1406 but unfortunately the branch that was selected was incorrect. We couldn't figure out a way to change it so this pull request should take the place of the old one.

### CODE REVIEW

File: src/npc/src/npc_move.c [hunk 1]
```diff
@@ -320,14 +323,16 @@ int auto_gen_movement(npc_mov_t *npc_mov, game_t *game)
...
-            int maxtime_in_room = 90000; // max time in room in ms, 90000 ms = 90 s
+        else if(npc->movement->mov_type == NPC_MOV_INDEFINITE) {
+            double speed = get_stat_current(npc->class->base_stats, "speed");
+            double multiplier = sqrt(100/speed);
+            int mintime_in_room = 30000 * multiplier; // min time in room in ms, 30000 ms = 30 s
+            int maxtime_in_room = 90000 * multiplier; // max time in room in ms, 90000 ms = 90 s
             int time_in_room = (rand() % (maxtime_in_room - mintime_in_room + 1)) + mintime_in_room;
-            rc = extend_path_indefinite(npc_mov, room_to_add, time_in_room);
+            rc = extend_path_indefinite(npc->movement, room_to_add, time_in_room);
 	      }
```
Comment (katie-gao) [inline src/npc/src/npc_move.c]: This is a small comment, but I would suggest lining up the brackets with the corresponding if/else if statements. So, in this case I would move the brackets back a few spaces to line with the else if statement.

File: src/npc/src/npc_move.c [hunk 2]
```diff
@@ -320,14 +323,16 @@ int auto_gen_movement(npc_mov_t *npc_mov, game_t *game)
...
         }
-        else if(npc_mov->mov_type == NPC_MOV_INDEFINITE) {
-            int mintime_in_room = 30000; // min time in room in ms, 30000 ms = 30 s
-            int maxtime_in_room = 90000; // max time in room in ms, 90000 ms = 90 s
+        else if(npc->movement->mov_type == NPC_MOV_INDEFINITE) {
+            double speed = get_stat_current(npc->class->base_stats, "speed");
+            double multiplier = sqrt(100/speed);
+            int mintime_in_room = 30000 * multiplier; // min time in room in ms, 30000 ms = 30 s
+            int maxtime_in_room = 90000 * multiplier; // max time in room in ms, 90000 ms = 90 s
             int time_in_room = (rand() % (maxtime_in_room - mintime_in_room + 1)) + mintime_in_room;
```
Comment (katie-gao) [inline src/npc/src/npc_move.c]: Can you guys check if this is in the 80 character line?

File: src/npc/src/npc_move.c [hunk 3]
```diff
@@ -320,14 +323,16 @@ int auto_gen_movement(npc_mov_t *npc_mov, game_t *game)
...
-            rc = extend_path_indefinite(npc_mov, room_to_add, time_in_room);
+            rc = extend_path_indefinite(npc->movement, room_to_add, time_in_room);
 	      }
 
         if(rc == FAILURE) {
```
Comment (katie-gao) [inline src/npc/src/npc_move.c]: Maybe I am not understanding the code correctly, but if it returns rc in both the if statement and right after, then is the if statement necessary? It might be redundant if it always returns rc.

File: src/npc/src/npc_move.c [hunk 4]
```diff
@@ -336,4 +341,4 @@ int auto_gen_movement(npc_mov_t *npc_mov, game_t *game)
     }
 
     return rc;
-}
+}
```
Comment (katie-gao) [inline src/npc/src/npc_move.c]: Overall, nice job adding the multiplier and updating the variables to match the changes. I think it is really cool you guys learned the hash table and random functions. I just made a few comments on formatting and had a few questions on the code, but it looks really good. Next, I would just think about how to test it. Also, I like how succinct you guys made the code.

File: src/npc/src/npc_move.c (hunk 3 above)
Comment (bvvill) [reply src/npc/src/npc_move.c]: i wondered the same thing too, but then i realized it's part of the loop, so if `rc` is ever `FAILURE` then it'll return and break out of the for-loop

File: src/playerclass/src/class.c [hunk 5]
```diff
@@ -91,25 +91,39 @@ int class_init(class_t* class, char* name, char* shortdesc, char* longdesc,
  * Paramaters:
  *  - base_class: the character's base class (their current class).
  *  - second_class: the class being added to the original class.
+ *  - succ: an out parameter that is set to SUCCESS if the length of the new
```
Comment (lilyehsani) [inline src/playerclass/src/class.c]: The changes in this file seem to be unrelated to NPC speed. Please remove them.

**Review by lilyehsani — CHANGES_REQUESTED** [review]
Looks good so far! One comment.

File: src/npc/src/npc_move.c [hunk 6]
```diff
@@ -302,13 +305,13 @@ int get_num_rooms(game_t *game)
...
 /* See npc_move.h */
-int auto_gen_movement(npc_mov_t *npc_mov, game_t *game)
+int auto_gen_movement(npc_t *npc, game_t *game)
 {
     room_list_t *head = get_all_rooms(game); // from include/game-state/game.h
     int rc = 0;
     int num_rooms, num_rooms_to_add;
 
-	if(npc_mov == NULL || head == NULL) {
+	if(npc->movement == NULL || head == NULL) {
```
Comment (lilyehsani) [inline src/npc/src/npc_move.c]: Chiventure uses [Allman Style](https://uchicago-cs.github.io/dev-guide/style_guide_c.html#indentation) brackets, please change to this (manually, NOT with the astyle command as that will change all chiventure files).

File: src/npc/src/npc_move.c (hunk 1 above)
Comment (Vincent-Zhang4135) [reply src/npc/src/npc_move.c]: got it! appreciate the minor suggestions!

File: src/npc/src/npc_move.c (hunk 2 above)
Comment (Vincent-Zhang4135) [reply src/npc/src/npc_move.c]: thanks! I fixed the comments to match the 80 character line convention

**Review by bvvill — APPROVED** [review]
Everything looks good to me now, I went ahead and changed the type of the time being used from int to double, to make future merges easier.

**Comment by Vincent-Zhang4135** [comment]
Thank you William helping resolve the tests for us!

**Review by katie-gao — APPROVED** [review]

**Review by lilyehsani — APPROVED** [review]
LGTM! Approved.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work! Like issues, PRs should have closing statements.
